Fix a few typos
id-contact/docs pull request #14
Opened 2021-04-07 09:43 UTC by arjenzijlstra

Left words like "plugin" and "setup" and any typos in strings in code blocks as they were.

2021-04-12 14:02 UTC, hdoordt requested changes
Very nice, thank you. One minor nitpick: 'video-call' should be 'video call'

2021-04-12 14:02 UTC, hdoordt commented on webdocs/docs/index.mdx
> +ID Contact is a system for setting up authenticated communication between end-users and an organisations support agents. The motivating use case for ID-Contact is for Dutch municipalities to verify c
video-call -> video call

2021-04-13 08:28 UTC, arjenzijlstra commented on webdocs/docs/index.mdx
> +ID Contact is a system for setting up authenticated communication between end-users and an organisations support agents. The motivating use case for ID-Contact is for Dutch municipalities to verify c
```suggestion
ID Contact is a system for setting up authenticated communication between end-users and an organisations support agents. The motivating use case for ID-Contact is for Dutch municipalities to verify citizen identity communicating over chat, telephone, video call or other remote communication channels.
```

2021-04-13 08:29 UTC, hdoordt approved these changes

2021-04-13 08:29 UTC, merged